### ISSUE TITLE
Weird behavior when swapping from encoding/json to github.com/goccy/go-json

### ISSUE THREAD

**Issue by lestrrat** [goccy/go-json#93]
```
% go version
go version go1.16beta1 darwin/arm64
```

In github.com/lestrrat-go/jwx ([topic/v1.1.0-marshal-optimize branch](https://github.com/lestrrat-go/jwx/tree/topic/v1.1.0-marshal-optimize), commit [bc72347](https://github.com/lestrrat-go/jwx/commit/bc72347ec2f562ed397aec12ef86dbabba4e2cb8)), if you just run some tests, it passes.

```
% make smoke
<snip>
PASS
ok  	github.com/lestrrat-go/jwx/examples	4.057s
ok  	github.com/lestrrat-go/jwx	(cached)
?   	github.com/lestrrat-go/jwx/cmd/jwx	[no test files]
<snip>
```

Now, apply the following patch

```diff
diff --git a/internal/json/json.go b/internal/json/json.go
index 0eaf063..f90e8bf 100644
--- a/internal/json/json.go
+++ b/internal/json/json.go
@@ -2,10 +2,10 @@ package json
 
 import (
        "bytes"
-       "encoding/json"
        "io"
        "sync"
 
+       "github.com/goccy/go-json"
        "github.com/lestrrat-go/jwx/internal/base64"
        "github.com/pkg/errors"
 )
```

Then run

```
make tidy   # runs go mod tidy where applicable
```

and then run some tests.

```
% make smoke
<snip>
--- FAIL: ExampleJWS_Message (0.00s)
got:
json: error calling MarshalJSON for type *jws.Message: failed to handle opcode. doesn't implement StructFieldOmitEmptyStringPtr
<snip>
```

Further more, run the following

```
cd jwk && go test
```

And then BOOOM

```
unexpected fault address 0x23a0000015fd4
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x23a0000015fd4 pc=0x23a0000015fd4]

goroutine 23 [running]:
runtime.throw(0x105298293, 0x5)
	/usr/local/go/src/runtime/panic.go:1112 +0x54 fp=0x14000167e30 sp=0x14000167e00 pc=0x104ef5204
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:737 +0x230 fp=0x14000167e70 sp=0x14000167e30 pc=0x104f0c7f0
github.com/lestrrat-go/jwx/jwk_test.TestECDSA.func3(0x14000103380)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwk/ecdsa_test.go:189 +0x134 fp=0x14000167f70 sp=0x14000167e80 pc=0x10528b064
testing.tRunner(0x14000103380, 0x1053fb868)
	/usr/local/go/src/testing/testing.go:1194 +0xe0 fp=0x14000167fc0 sp=0x14000167f70 pc=0x104f9e4f0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x14000167fc0 sp=0x14000167fc0 pc=0x104f2b634
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x21c

goroutine 1 [chan receive]:
testing.(*T).Run(0x14000102a80, 0x1052994cb, 0x9, 0x1053fb888, 0x600998f7)
	/usr/local/go/src/testing/testing.go:1240 +0x238
testing.runTests.func1(0x14000102900)
	/usr/local/go/src/testing/testing.go:1512 +0x74
testing.tRunner(0x14000102900, 0x14000193da8)
	/usr/local/go/src/testing/testing.go:1194 +0xe0
testing.runTests(0x1400012c180, 0x1056310c0, 0x12, 0x12, 0xbffa84b3de79fc98, 0x8bb2dc144d, 0x105637340, 0x104f9609c)
	/usr/local/go/src/testing/testing.go:1510 +0x284
testing.(*M).Run(0x1400018a080, 0x0)
	/usr/local/go/src/testing/testing.go:1418 +0x1b4
main.main()
	_testmain.go:79 +0x14c

goroutine 19 [chan receive]:
testing.(*T).Run(0x14000103380, 0x1052a525d, 0x1d, 0x1053fb868, 0x2e3b599a98d01)
	/usr/local/go/src/testing/testing.go:1240 +0x238
github.com/lestrrat-go/jwx/jwk_test.TestECDSA(0x14000102a80)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwk/ecdsa_test.go:170 +0xa0
testing.tRunner(0x14000102a80, 0x1053fb888)
	/usr/local/go/src/testing/testing.go:1194 +0xe0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x21c
exit status 2
FAIL	github.com/lestrrat-go/jwx/jwk	0.392s
```

**Comment by lestrrat** [comment]
I traced the offending call for my first problem

> json: error calling MarshalJSON for type *jws.Message: failed to handle opcode. doesn't implement StructFieldOmitEmptyStringPtr

```diff
diff --git a/encode_vm.go b/encode_vm.go
index 01f3fa0..9ede3a0 100644
--- a/encode_vm.go
+++ b/encode_vm.go
@@ -56,7 +56,7 @@ func (e *Encoder) run(ctx *encodeRuntimeContext, b []byte, code *opcode) ([]byte
        for {
                switch code.op {
                default:
-                       return nil, fmt.Errorf("failed to handle opcode. doesn't implement %s", code.op)
+                       return nil, fmt.Errorf("(Encoder.run)failed to handle opcode. doesn't implement %s", code.op)
                case opPtr:
                        ptr := load(ctxptr, code.idx)
                        code = code.next
diff --git a/encode_vm_escaped.go b/encode_vm_escaped.go
index 0345338..7c1cada 100644
--- a/encode_vm_escaped.go
+++ b/encode_vm_escaped.go
@@ -6,6 +6,7 @@ import (
        "fmt"
        "math"
        "reflect"
+       "runtime/debug"
        "sort"
        "unsafe"
 )
@@ -18,7 +19,8 @@ func (e *Encoder) runEscaped(ctx *encodeRuntimeContext, b []byte, code *opcode)
        for {
                switch code.op {
                default:
-                       return nil, fmt.Errorf("failed to handle opcode. doesn't implement %s", code.op)
+                       fmt.Printf("%s", debug.Stack())
+                       return nil, fmt.Errorf("(Encoder.runEscaped) failed to handle opcode. doesn't implement %s", code.op)
                case opPtr:
                        ptr := load(ctxptr, code.idx)
                        code = code.next
diff --git a/encode_vm_escaped_indent.go b/encode_vm_escaped_indent.go
index 785c0a2..0b4210b 100644
--- a/encode_vm_escaped_indent.go
+++ b/encode_vm_escaped_indent.go
@@ -19,7 +19,7 @@ func (e *Encoder) runEscapedIndent(ctx *encodeRuntimeContext, b []byte, code *op
        for {
                switch code.op {
                default:
-                       return nil, fmt.Errorf("failed to handle opcode. doesn't implement %s", code.op)
+                       return nil, fmt.Errorf("(Encoder.runEscapeedIndent) failed to handle opcode. doesn't implement %s", code.op)
                case opPtr:
                        ptr := load(ctxptr, code.idx)
                        code = code.next
diff --git a/encode_vm_indent.go b/encode_vm_indent.go
index 3507a46..d1abad6 100644
--- a/encode_vm_indent.go
+++ b/encode_vm_indent.go
@@ -19,7 +19,7 @@ func (e *Encoder) runIndent(ctx *encodeRuntimeContext, b []byte, code *opcode) (
        for {
                switch code.op {
                default:
-                       return nil, fmt.Errorf("failed to handle opcode. doesn't implement %s", code.op)
+                       return nil, fmt.Errorf("(Encoder.runIndent) failed to handle opcode. doesn't implement %s", code.op)
                case opPtr:
                        ptr := load(ctxptr, code.idx)
                        code = code.next
                        
```
to this.

```
goroutine 1 [running]:
runtime/debug.Stack(0x1400070087a, 0x1400023b640, 0x4)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/goccy/go-json.(*Encoder).runEscaped(0x140003e8380, 0x140002be2d0, 0x14000700800, 0x7f, 0x400, 0x140007040f0, 0x14000700800, 0x10, 0x400, 0x0, ...)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode_vm_escaped.go:22 +0x950
github.com/goccy/go-json.(*Encoder).encode(0x140003e8380, 0x14000799b28, 0x14000386100, 0x140003e8380, 0x14000799a88, 0x1026bc5b0, 0x102b94820, 0x102935fa0)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode.go:245 +0x684
github.com/goccy/go-json.(*Encoder).encodeForMarshal(0x140003e8380, 0x14000799b28, 0x140003e8300, 0x10290bfa0, 0x0, 0x1400048ad20, 0x129d0bb00, 0x0)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode.go:164 +0x38
github.com/goccy/go-json.MarshalWithOption(0x10290bfa0, 0x14000380b80, 0x0, 0x0, 0x0, 0x14000380b80, 0x14000799ca8, 0x14000380b80, 0x56, 0x14000380b80)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/json.go:186 +0xdc
github.com/goccy/go-json.Marshal(...)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/json.go:158
github.com/lestrrat-go/jwx/internal/json.Marshal(0x10290bfa0, 0x14000380b80, 0x10290bfa0, 0x14000380b80, 0x2, 0x140002c5a40, 0x1)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/json/json.go:56 +0x38
github.com/lestrrat-go/jwx/jws.Message.MarshalJSON(0x14000740000, 0x46, 0x46, 0x140002c59a0, 0x2, 0x2, 0x0, 0x129eb23d0, 0x0, 0x0, ...)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jws/message.go:282 +0x414
github.com/goccy/go-json.(*Encoder).runEscapedIndent(0x140003e8000, 0x140002be000, 0x14000300800, 0x0, 0x400, 0x140004cd4a0, 0x14000217000, 0x100, 0x100, 0x20, ...)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode_vm_escaped_indent.go:246 +0x4210
github.com/goccy/go-json.(*Encoder).encode(0x140003e8000, 0x140004739e8, 0x1400031ae00, 0x1027c8fc6, 0x2, 0x8, 0x102b94820, 0x2)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode.go:239 +0x5b4
github.com/goccy/go-json.(*Encoder).encodeForMarshal(0x140003e8000, 0x140004739e8, 0x0, 0x1400031ae28, 0x2, 0x8, 0x14000380800, 0x0)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/encode.go:164 +0x38
github.com/goccy/go-json.MarshalIndentWithOption(0x102908500, 0x140003086f0, 0x0, 0x0, 0x1027c8fc6, 0x2, 0x0, 0x0, 0x0, 0x2, ...)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/json.go:214 +0xf0
github.com/goccy/go-json.MarshalIndent(...)
	/Users/lestrrat/dev/src/github.com/goccy/go-json/json.go:199
github.com/lestrrat-go/jwx/internal/json.MarshalIndent(0x102908500, 0x140003086f0, 0x0, 0x0, 0x1027c8fc6, 0x2, 0x1, 0x2, 0x1028cf860, 0x14000688900, ...)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/json/json.go:61 +0x58
github.com/lestrrat-go/jwx/examples_test.ExampleJWS_Message()
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/examples/jws_example_test.go:197 +0x5c0
testing.runExample(0x1027cde32, 0x12, 0x102936f18, 0x1027f8a3c, 0x358, 0x0, 0x0)
	/usr/local/go/src/testing/run_example.go:63 +0x1b8
testing.runExamples(0x1400079feb8, 0x102b84cc0, 0xf, 0xf, 0xbffa9d9e0469c6a8)
	/usr/local/go/src/testing/example.go:44 +0x128
testing.(*M).Run(0x14000192000, 0x0)
	/usr/local/go/src/testing/testing.go:1419 +0x214
main.main()
	_testmain.go:71 +0x14c
json: error calling MarshalJSON for type *jws.Message: (Encoder.runEscaped) failed to handle opcode. doesn't implement StructFieldOmitEmptyStringPtr
```

Upon inspecting my code, a few things that got my attention

* I'm making a call to json.Marshal from within MarshalJSON() - I call `json.Marshal(*jws.Message)`, and `(jws.Message).MrashalJSON()` creates another struct within it, and then calls `json.Marshal` on it
* The object that is being marshaled at `/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jws/message.go:282` is an unexported type
* It strikes me slightly odd that the error message is saying `*jws.Message` is the problem -- because it's failing when it's trying to marshal `jws.messageProxy`

I suppose I can workaround this particular problem by removing the call to `json.Marshal` from within `(jws.Message).MarshalJSON`, but I think this should work without such modification.

**Comment by lestrrat** [comment]
As I suspected, [changing `(jws.Message).MarshalJSON()` to **NOT** use `json.Marshal` against a unexported struct ](https://github.com/lestrrat-go/jwx/commit/e197c0b4f6e3cc4e3a88b7a8e779e2c3f3a60d81#diff-53147420851a4a4017650d24d6176ea4a4157d83ef39f852ed74c1c07bc8b27b)from within it fixed the first problem.

I think you have a problem when dealing win structs that are not exported. 


I'm still not sure how to tackle the segfault, as I'm not sure where my code is being called from (if at all)

**Comment by Warashi** [comment]
I reproduced problem
https://play.golang.org/p/ax3SkvRyWRV

omitempty of `*string` seems not implemented

**Comment by goccy** [comment]
Thank you for your report. 
For the first issue, since I just committed a String operation related fix the other day and I think it will work on the master branch. 
The second problem, as reported, seems to be a bug with structs within only unexported fields.

**Comment by lestrrat** [comment]
@goccy I'm not sure if it's fixed in master. From [github.com/lestrrat-go/jwk@bc72347ec](https://github.com/lestrrat-go/jwx/commit/bc72347ec2f562ed397aec12ef86dbabba4e2cb8) (this is the commit at which I'm still calling `json.Marshal` from within `(jws.Message).MarshalJSON()`), I did

```
% go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master
% cd examples && go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master && cd ..
% cd bench && go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master && cd ..
% make tidy
```

Then ran tests in my `examples` directory, and tests still fail:

```
% go test
<snip>
json: error calling MarshalJSON for type *jws.Message: failed to handle opcode. doesn't implement StructFieldOmitEmptyStringPtr
</snip>
```

Just as a sanity check, the file `examples/go.sum` is pointing to the correct version

```diff
diff --git a/examples/go.sum b/examples/go.sum
index 53de14d..9a91655 100644
--- a/examples/go.sum
+++ b/examples/go.sum
@@ -2,6 +2,8 @@ github.com/cloudflare/circl v1.0.1-0.20210104183656-96a0695de3c3 h1:tpTW2GMi0DOd
 github.com/cloudflare/circl v1.0.1-0.20210104183656-96a0695de3c3/go.mod h1:l2CvGr3DNS9Egif8pwQqJ45Ci9Y/PPs0XJHTcRKbGBQ=
 github.com/davecgh/go-spew v1.1.0 h1:ZDRjVQ15GmhC3fiQ8ni8+OwkZQO4DARzQgrnXU1Liz8=
 github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
+github.com/goccy/go-json v0.3.2-0.20210120153452-020aaffd4c5e h1:PfobGZaFJPTdKG6arj2/RMpflTNnb39kbNkmyQUzPbw=
+github.com/goccy/go-json v0.3.2-0.20210120153452-020aaffd4c5e/go.mod h1:6MelG93GURQebXPDq3khkgXZkazVtN9CRI+MGFi0w8I=
 github.com/lestrrat-go/backoff/v2 v2.0.3 h1:2ABaTa5ifB1L90aoRMjaPa97p0WzzVe93Vggv8oZftw=
 github.com/lestrrat-go/backoff/v2 v2.0.3/go.mod h1:mU93bMXuG27/Y5erI5E9weqavpTX5qiVFZI4uXAX0xk=
 github.com/lestrrat-go/codegen v0.0.0-20210115164254-686308008f83/go.mod h1:SGL1VXENaMr0dLvl58itf0mf0zurpKkhLj7zChlGnt8=
diff --git a/go.mod b/go.mod
index 29287f0..a74fe90 100644
```

So... different problem, maybe?

**Comment by goccy** [comment]
I try to fix this problem with https://github.com/goccy/go-json/pull/94 .
Currently, I have confirmed that all errors except the output by `make smoke` have been fixed.

**Comment by lestrrat** [comment]
@goccy indeed. As of 305e858 the failures in `jwk` directory are gone, and failures in `examples` directory remain

**Comment by goccy** [comment]
I was debugging with `go mod edit`.
By doing `go mod edit` in the same way under the examples directory, the error caused by `make smoke` disappeared.

```
$ cd jwx
$ go mod edit -replace github.com/goccy/go-json=../go-json
$ cd examples
$ go mod edit -replace github.com/goccy/go-json=../../go-json
```

Apparently, the modules will not be replaced unless you replace them even under examples ( sub directory ) .

**Comment by goccy** [comment]
I released `v0.3.2` ( https://github.com/goccy/go-json/releases/tag/v0.3.2 ) to fix this problem .

**Comment by Warashi** [comment]
this code ran successfully with v0.3.2
https://github.com/goccy/go-json/issues/93#issuecomment-765055758

**Comment by lestrrat** [comment]
> Apparently, the modules will not be replaced unless you replace them even under examples ( sub directory ) .

@goccy that's because from Go's viewpoint, every directory containing a go.mod is considered to be separate module. I have separate go.mod files in `examples` and `bench`, because otherwise it will (well, actually right now on `examples` does that, but...) cause users of my library to pull in optional modules, such as `github.com/cloudflare/circl` in `examples`

That's why I have an explicit 

```
% go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master
% cd examples && go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master && cd ..
% cd bench && go mod edit -replace github.com/goccy/go-json=github.com/goccy/go-json@master && cd ..
% make tidy
```

:)

**Comment by lestrrat** [comment]
@goccy I still get errors (Note: I'm NOT using HEAD of topic/v1.1.0-marshal-optimize, I'm using bc72347ec2f562ed397aec12ef86dbabba4e2cb8 because I "fixed" the error in `examples` by removing `json.Marshal` from the code)

```
% go get github.com/goccy/go-json@v0.3.2
% make tidy
% make smoke
<snip>
--- FAIL: ExampleJWS_Message (0.00s)
got:
json: error calling MarshalJSON for type *jws.Message: failed to handle opcode. doesn't implement StructFieldOmitEmptyStringPtr
```

I'm definitely using v0.3.2

```diff
diff --git a/examples/go.sum b/examples/go.sum
index 53de14d..efe494f 100644
--- a/examples/go.sum
+++ b/examples/go.sum
@@ -2,6 +2,8 @@ github.com/cloudflare/circl v1.0.1-0.20210104183656-96a0695de3c3 h1:tpTW2GMi0DOd
 github.com/cloudflare/circl v1.0.1-0.20210104183656-96a0695de3c3/go.mod h1:l2CvGr3DNS9Egif8pwQqJ45Ci9Y/PPs0XJHTcRKbGBQ=
 github.com/davecgh/go-spew v1.1.0 h1:ZDRjVQ15GmhC3fiQ8ni8+OwkZQO4DARzQgrnXU1Liz8=
 github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
+github.com/goccy/go-json v0.3.2 h1:yDfC0s3cikXMUWa97C6I3If0uSbcM3vLyUgGnn/vUtY=
+github.com/goccy/go-json v0.3.2/go.mod h1:6MelG93GURQebXPDq3khkgXZkazVtN9CRI+MGFi0w8I=
 github.com/lestrrat-go/backoff/v2 v2.0.3 h1:2ABaTa5ifB1L90aoRMjaPa97p0WzzVe93Vggv8oZftw=
 github.com/lestrrat-go/backoff/v2 v2.0.3/go.mod h1:mU93bMXuG27/Y5erI5E9weqavpTX5qiVFZI4uXAX0xk=
 github.com/lestrrat-go/codegen v0.0.0-20210115164254-686308008f83/go.mod h1:SGL1VXENaMr0dLvl58itf0mf0zurpKkhLj7zChlGnt8=
 ```

**Comment by goccy** [comment]
Oh... I also reproduced it !
I will fix it as soon as possible ...!

**Comment by Warashi** [comment]
I also reproduced it
https://play.golang.org/p/kxAvr02st4c
struct with 3 `*string` fields seems to fail

**Comment by goccy** [comment]
I was able to confirm that this fix ( #95 ) did not cause an error.
However, I sometimes got an error when testing with `go test -race` , so I'm investigating the cause ....

**Comment by lestrrat** [comment]
As of 20b409ed1f64 I get the following at the end of the test :/

```
<snip>
PASS
ok  	github.com/lestrrat-go/jwx/examples	4.369s
ok  	github.com/lestrrat-go/jwx	(cached)
?   	github.com/lestrrat-go/jwx/cmd/jwx	[no test files]
ok  	github.com/lestrrat-go/jwx/internal/base64	(cached)
?   	github.com/lestrrat-go/jwx/internal/blackmagic	[no test files]
?   	github.com/lestrrat-go/jwx/internal/cmd/genreadfile	[no test files]
?   	github.com/lestrrat-go/jwx/internal/ecutil	[no test files]
?   	github.com/lestrrat-go/jwx/internal/fs	[no test files]
?   	github.com/lestrrat-go/jwx/internal/iter	[no test files]
?   	github.com/lestrrat-go/jwx/internal/jose	[no test files]
?   	github.com/lestrrat-go/jwx/internal/json	[no test files]
?   	github.com/lestrrat-go/jwx/internal/jwxtest	[no test files]
ok  	github.com/lestrrat-go/jwx/internal/keyconv	(cached)
?   	github.com/lestrrat-go/jwx/internal/pool	[no test files]
ok  	github.com/lestrrat-go/jwx/jwa	(cached)
?   	github.com/lestrrat-go/jwx/jwa/internal/cmd/gentypes	[no test files]
ok  	github.com/lestrrat-go/jwx/jwe	(cached)
ok  	github.com/lestrrat-go/jwx/jwe/internal/aescbc	(cached)
ok  	github.com/lestrrat-go/jwx/jwe/internal/cipher	(cached)
?   	github.com/lestrrat-go/jwx/jwe/internal/cmd/genheader	[no test files]
ok  	github.com/lestrrat-go/jwx/jwe/internal/concatkdf	(cached)
?   	github.com/lestrrat-go/jwx/jwe/internal/content_crypt	[no test files]
ok  	github.com/lestrrat-go/jwx/jwe/internal/keyenc	(cached)
?   	github.com/lestrrat-go/jwx/jwe/internal/keygen	[no test files]
ok  	github.com/lestrrat-go/jwx/jwk	(cached)
?   	github.com/lestrrat-go/jwx/jwk/internal/cmd/genheader	[no test files]
ok  	github.com/lestrrat-go/jwx/jws	(cached)
?   	github.com/lestrrat-go/jwx/jws/internal/cmd/genheader	[no test files]
unexpected fault address 0x19080807b5f504b4
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x19080807b5f504b4 pc=0x102b70620]

goroutine 60 [running]:
runtime.throw(0x1030c7d57, 0x5)
	/usr/local/go/src/runtime/panic.go:1112 +0x54 fp=0xc000198b60 sp=0xc000198b30 pc=0x102b3bab4
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:737 +0x230 fp=0xc000198ba0 sp=0xc000198b60 pc=0x102b54430
aeshashbody(0x1031eb788, 0x0, 0x102b167a0, 0x102b4defc, 0xc000214018, 0x102b55507, 0x0, 0x0, 0x0, 0x1031cc880, ...)
	/usr/local/go/src/runtime/asm_arm64.s:754 +0x2d0 fp=0xc000198bb0 sp=0xc000198bb0 pc=0x102b70620
runtime.mapiternext(0xc000198f48)
	/usr/local/go/src/runtime/map.go:921 +0x318 fp=0xc000198c40 sp=0xc000198bb0 pc=0x102b16ab8
runtime.mapiterinit(0x1031cc880, 0xc000198d28, 0xc000198f48)
	/usr/local/go/src/runtime/map.go:848 +0x1b0 fp=0xc000198c80 sp=0xc000198c40 pc=0x102b16650
github.com/lestrrat-go/jwx/jwt.(*stdToken).iterate(0xc000234050, 0x103228058, 0xc000200140, 0xc000210780)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_gen.go:288 +0x208 fp=0xc000198fb0 sp=0xc000198c80 pc=0x10309cbe8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0xc000198fb0 sp=0xc000198fb0 pc=0x102b72f04
created by github.com/lestrrat-go/jwx/jwt.(*stdToken).Iterate
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_gen.go:381 +0x70

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000106480)
	/usr/local/go/src/testing/testing.go:1160 +0x278
testing.tRunner(0xc000106480, 0xc00018dcb8)
	/usr/local/go/src/testing/testing.go:1198 +0x194
testing.runTests(0xc00012e3c0, 0x1034489e0, 0xd, 0xd, 0xbfface7ace7ff9a0, 0x8bb2e7e0f9, 0x1034593a0, 0x102b13ee0)
	/usr/local/go/src/testing/testing.go:1510 +0x508
testing.(*M).Run(0xc000190080, 0x0)
	/usr/local/go/src/testing/testing.go:1418 +0x2d4
main.main()
	_testmain.go:69 +0x224

goroutine 19 [runnable]:
math/big.nat.montgomery(0xc0000ce280, 0x10, 0x26, 0xc0000da5a0, 0x10, 0x24, 0xc0000da5a0, 0x10, 0x24, 0xc0000c0000, ...)
	/usr/local/go/src/math/big/nat.go:213 +0x404
math/big.nat.expNNMontgomery(0xc0000da5a0, 0x10, 0x24, 0xc0000c08c0, 0x10, 0x14, 0xc0000c0780, 0x10, 0x14, 0xc0000c0000, ...)
	/usr/local/go/src/math/big/nat.go:1449 +0x684
math/big.nat.expNN(0xc0000c0960, 0x10, 0x14, 0xc0000c08c0, 0x10, 0x14, 0xc0000c0780, 0x10, 0x14, 0xc0000c0000, ...)
	/usr/local/go/src/math/big/nat.go:1262 +0x768
math/big.nat.probablyPrimeMillerRabin(0xc0000c0000, 0x10, 0x14, 0x15, 0xc0256208d0332f01, 0x14)
	/usr/local/go/src/math/big/prime.go:106 +0x3e0
math/big.(*Int).ProbablyPrime(0xc0000be000, 0x14, 0xc000152000)
	/usr/local/go/src/math/big/prime.go:78 +0x36c
crypto/rand.Prime(0x1032230f8, 0xc000116210, 0x400, 0xc000096060, 0xc000051ba8, 0x102b0ce9c)
	/usr/local/go/src/crypto/rand/util.go:99 +0x21c
crypto/rsa.GenerateMultiPrimeKey(0x1032230f8, 0xc000116210, 0x2, 0x800, 0xc0001066c0, 0xc000106710, 0xc0001066f8)
	/usr/local/go/src/crypto/rsa/rsa.go:302 +0x120
crypto/rsa.GenerateKey(...)
	/usr/local/go/src/crypto/rsa/rsa.go:242
github.com/lestrrat-go/jwx/internal/jwxtest.GenerateRsaKey(0xc000106600, 0x102b5c4e4, 0xc000051de8)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/jwxtest/jwxtest.go:28 +0x5c
github.com/lestrrat-go/jwx/jwt_test.TestJWTParse(0xc000106600)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:42 +0x38
testing.tRunner(0xc000106600, 0x10321cd20)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 20 [runnable]:
math/big.nat.montgomery(0xc0003bb200, 0x10, 0x24, 0xc0003b6000, 0x10, 0x26, 0xc0003b6000, 0x10, 0x26, 0xc0003a8000, ...)
	/usr/local/go/src/math/big/nat.go:213 +0x404
math/big.nat.expNNMontgomery(0xc0003bb200, 0x10, 0x24, 0xc0003a83c0, 0x10, 0x14, 0xc0003a8280, 0x10, 0x14, 0xc0003a8000, ...)
	/usr/local/go/src/math/big/nat.go:1450 +0x6f4
math/big.nat.expNN(0xc0003a8460, 0x10, 0x14, 0xc0003a83c0, 0x10, 0x14, 0xc0003a8280, 0x10, 0x14, 0xc0003a8000, ...)
	/usr/local/go/src/math/big/nat.go:1262 +0x768
math/big.nat.probablyPrimeMillerRabin(0xc0003a8000, 0x10, 0x14, 0x15, 0x4f368a54e53e6101, 0x1)
	/usr/local/go/src/math/big/prime.go:106 +0x3e0
math/big.(*Int).ProbablyPrime(0xc00039e020, 0x14, 0xc00004caf8)
	/usr/local/go/src/math/big/prime.go:78 +0x36c
crypto/rand.Prime(0x1032230f8, 0xc000116210, 0x400, 0xc000398020, 0xc00004cbf8, 0x102b0cdf8)
	/usr/local/go/src/crypto/rand/util.go:99 +0x21c
crypto/rsa.GenerateMultiPrimeKey(0x1032230f8, 0xc000116210, 0x2, 0x800, 0xc0001069c0, 0xc000106a10, 0xc0001069f8)
	/usr/local/go/src/crypto/rsa/rsa.go:302 +0x120
crypto/rsa.GenerateKey(...)
	/usr/local/go/src/crypto/rsa/rsa.go:242
github.com/lestrrat-go/jwx/internal/jwxtest.GenerateRsaKey(0xc000106900, 0x102c0c12c, 0xc000119ad0)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/jwxtest/jwxtest.go:28 +0x5c
github.com/lestrrat-go/jwx/jwt_test.TestJWTParseVerify(0xc000106900)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:113 +0x38
testing.tRunner(0xc000106900, 0x10321cd18)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 21 [runnable]:
testing.(*T).Run(0xc000106c00, 0x1030c887e, 0x8, 0x10321cd80, 0xc00003aeb8)
	/usr/local/go/src/testing/testing.go:1240 +0x45c
github.com/lestrrat-go/jwx/jwt_test.TestValidateClaims(0xc000106c00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:269 +0x58
testing.tRunner(0xc000106c00, 0x10321cd88)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 22 [chan receive]:
testing.tRunner.func1(0xc000106f00)
	/usr/local/go/src/testing/testing.go:1160 +0x278
testing.tRunner(0xc000106f00, 0x10321cd78)
	/usr/local/go/src/testing/testing.go:1198 +0x194
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 24 [chan receive]:
testing.tRunner.func1(0xc000107500)
	/usr/local/go/src/testing/testing.go:1160 +0x278
testing.tRunner(0xc000107500, 0x10321cd70)
	/usr/local/go/src/testing/testing.go:1198 +0x194
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 25 [runnable]:
math/big.nat.divBasic(0xc0001d1ce0, 0x11, 0x15, 0xc0001d40f0, 0x1a, 0x1d, 0xc0004140b0, 0x9, 0x15)
	/usr/local/go/src/math/big/nat.go:745 +0x62c
math/big.nat.divLarge(0x0, 0x0, 0x0, 0xc0001d40f0, 0x19, 0x1d, 0xc0001d40f0, 0x19, 0x1d, 0xc000102ba0, ...)
	/usr/local/go/src/math/big/nat.go:725 +0x204
math/big.nat.div(0x0, 0x0, 0x0, 0xc0001d40f0, 0x19, 0x1d, 0xc0001d40f0, 0x19, 0x1d, 0xc000102ba0, ...)
	/usr/local/go/src/math/big/nat.go:672 +0x2f4
math/big.(*Int).QuoRem(0xc0001216a8, 0xc000153860, 0xc0001526e0, 0xc000153860, 0x1d, 0xc0001d40f0)
	/usr/local/go/src/math/big/int.go:239 +0x13c
math/big.(*Int).Mod(0xc000153860, 0xc000153860, 0xc0001526e0, 0xc000153860)
	/usr/local/go/src/math/big/int.go:270 +0x80
crypto/elliptic.(*CurveParams).addJacobian(0xc000162b40, 0xc0001527a0, 0xc0001527e0, 0xc000121c48, 0xc000153820, 0xc000153800, 0xc000153840, 0xc000153740, 0xc000153760, 0xc000153780)
	/usr/local/go/src/crypto/elliptic/elliptic.go:174 +0x1034
crypto/elliptic.(*CurveParams).ScalarMult(0xc000162b40, 0xc0001527a0, 0xc0001527e0, 0xc00017a417, 0x41, 0x41, 0x0, 0x0)
	/usr/local/go/src/crypto/elliptic/elliptic.go:268 +0x11c
crypto/elliptic.(*CurveParams).ScalarBaseMult(0xc000162b40, 0xc00017a417, 0x41, 0x41, 0x48, 0x48)
	/usr/local/go/src/crypto/elliptic/elliptic.go:278 +0x80
crypto/ecdsa.GenerateKey(0x103228d08, 0xc000162b40, 0x1032230f8, 0xc000116210, 0xc000162a40, 0xc000106480, 0xc000107740)
	/usr/local/go/src/crypto/ecdsa/ecdsa.go:158 +0x19c
github.com/lestrrat-go/jwx/internal/jwxtest.GenerateEcdsaKey(0xc000107680, 0xc00019ce18, 0x158dc4945)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/jwxtest/jwxtest.go:55 +0x9c
github.com/lestrrat-go/jwx/jwt_test.TestSignErrors(0xc000107680)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:416 +0x30
testing.tRunner(0xc000107680, 0x10321cd30)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 26 [runnable]:
math/rand.(*rngSource).Seed(0xc00040d500, 0xc132f62131f82e43)
	/usr/local/go/src/math/rand/rng.go:204 +0x1ec
math/rand.NewSource(...)
	/usr/local/go/src/math/rand/rand.go:46
math/big.nat.probablyPrimeMillerRabin(0xc000408000, 0x10, 0x14, 0x15, 0x99b7c9a42046bc01, 0x1)
	/usr/local/go/src/math/big/prime.go:93 +0x1bc
math/big.(*Int).ProbablyPrime(0xc000406000, 0x14, 0xc0000c7ae8)
	/usr/local/go/src/math/big/prime.go:78 +0x36c
crypto/rand.Prime(0x1032230f8, 0xc000116210, 0x400, 0xc000402000, 0xc00019db78, 0x102b0ce9c)
	/usr/local/go/src/crypto/rand/util.go:99 +0x21c
crypto/rsa.GenerateMultiPrimeKey(0x1032230f8, 0xc000116210, 0x2, 0x800, 0xc000107a40, 0xc000107a90, 0xc000107a78)
	/usr/local/go/src/crypto/rsa/rsa.go:302 +0x120
crypto/rsa.GenerateKey(...)
	/usr/local/go/src/crypto/rsa/rsa.go:242
github.com/lestrrat-go/jwx/internal/jwxtest.GenerateRsaKey(0xc000107980, 0x102c0c22c, 0xc00003ae68)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/jwxtest/jwxtest.go:28 +0x5c
github.com/lestrrat-go/jwx/jwt_test.TestSignJWK(0xc000107980)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:443 +0x38
testing.tRunner(0xc000107980, 0x10321cd38)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 34 [select]:
github.com/lestrrat-go/iter/mapiter.(*iter).Next(0xc000246000, 0x103228058, 0xc000200140, 0x103225100)
	/Users/lestrrat/dev/pkg/mod/github.com/lestrrat-go/iter@v0.0.0-20200422075355-fc1769541911/mapiter/mapiter.go:95 +0x144
github.com/lestrrat-go/jwx/jwt.stdToken.MarshalJSON(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000204160, 0x0, 0x0, 0x0, 0xc000198d28, ...)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_gen.go:332 +0x1d0
github.com/goccy/go-json.(*Encoder).runEscaped(0xc000232000, 0xc000234000, 0xc000230400, 0x0, 0x400, 0xc0002a41e0, 0xc000198938, 0x102b1d81c, 0xc0001989e8, 0x102b13ee0, ...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode_vm_escaped.go:240 +0x70b0
github.com/goccy/go-json.(*Encoder).encode(0xc000232000, 0xc000198bf0, 0x0, 0x0, 0x0, 0x10321be40, 0x4, 0xc000232000)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:209 +0x5dc
github.com/goccy/go-json.(*Encoder).EncodeWithOption(0xc000232000, 0x1032060a0, 0xc000245d58, 0x0, 0x0, 0x0, 0x0, 0x102b5a201)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:115 +0xec
github.com/goccy/go-json.(*Encoder).Encode(...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:104
github.com/lestrrat-go/jwx/jwt_test.TestReadFile(0xc000082600)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:475 +0x1d0
testing.tRunner(0xc000082600, 0x10321cd28)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 35 [runnable]:
testing.(*T).Run(0xc000082900, 0x1030c867e, 0x8, 0x10321cd08, 0xc00000c201)
	/usr/local/go/src/testing/testing.go:1240 +0x45c
github.com/lestrrat-go/jwx/jwt_test.TestHeader(0xc000082900)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_test.go:91 +0x53c
testing.tRunner(0xc000082900, 0x10321cd10)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 36 [runnable]:
github.com/goccy/go-json.encodeEscapedString(0xc00029ec00, 0x2, 0x400, 0x1030c8062, 0x6, 0x0, 0x0, 0x0)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode_string.go:824 +0x11c8
github.com/goccy/go-json.(*Encoder).runEscaped(0xc0002a20e0, 0xc0002900f0, 0xc00029ec00, 0x1, 0x400, 0xc0002a4d20, 0xc0002a8838, 0x102b4f728, 0xc0002a88d8, 0x102b13ee0, ...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode_vm_escaped.go:140 +0x6944
github.com/goccy/go-json.(*Encoder).encode(0xc0002a20e0, 0xc0002c0ae0, 0x0, 0x10309ea7c, 0x102b194a0, 0x10309ea54, 0xc0002b6005, 0x2)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:245 +0xbe0
github.com/goccy/go-json.(*Encoder).EncodeWithOption(0xc0002a20e0, 0x1031bb1a0, 0xc000296078, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:115 +0xec
github.com/goccy/go-json.(*Encoder).Encode(...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:104
github.com/lestrrat-go/jwx/jwt.stdToken.MarshalJSON(0xc00028e030, 0x3, 0x3, 0xc000296048, 0xc000296000, 0x0, 0xc000292000, 0xc000296030, 0xc000292010, 0xc00028e000, ...)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_gen.go:367 +0x7c0
github.com/goccy/go-json.(*Encoder).runEscapedIndent(0xc0002a2000, 0xc000290050, 0xc00029e400, 0x0, 0x400, 0xc0002a41e0, 0x12b37ed00, 0x0, 0xc00019a958, 0x102b1d81c, ...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode_vm_escaped_indent.go:253 +0x84f0
github.com/goccy/go-json.(*Encoder).encode(0xc0002a2000, 0xc00019acc8, 0xc000294000, 0x6, 0xc00019abc8, 0x102b0dafc, 0x8, 0xc000294010)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:239 +0xa80
github.com/goccy/go-json.(*Encoder).encodeForMarshal(0xc0002a2000, 0xc00019acc8, 0x0, 0xc000294010, 0x2, 0x8, 0xc00019ad68, 0x1030baaf8)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/encode.go:164 +0x3c
github.com/goccy/go-json.MarshalIndentWithOption(0x1032060a0, 0xc000290000, 0x0, 0x0, 0x1030c75a1, 0x2, 0x0, 0x0, 0x0, 0xc000296048, ...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/json.go:214 +0x254
github.com/goccy/go-json.MarshalIndent(...)
	/Users/lestrrat/dev/pkg/mod/github.com/goccy/go-json@v0.3.3-0.20210122110857-20b409ed1f64/json.go:199
github.com/lestrrat-go/jwx/internal/json.MarshalIndent(0x1032060a0, 0xc000290000, 0x0, 0x0, 0x1030c75a1, 0x2, 0x0, 0x102b5c4e4, 0xc00019ade8, 0x102b5cbd4, ...)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/internal/json/json.go:64 +0x5c
github.com/lestrrat-go/jwx/jwt_test.TestTokenMarshal(0xc000082c00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_test.go:141 +0x538
testing.tRunner(0xc000082c00, 0x10321cd40)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 37 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000082f00)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestToken(0xc000082f00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_test.go:162 +0x34
testing.tRunner(0xc000082f00, 0x10321cd48)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 38 [chan receive]:
testing.tRunner.func1(0xc000083200)
	/usr/local/go/src/testing/testing.go:1160 +0x278
testing.tRunner(0xc000083200, 0x10321ccf8)
	/usr/local/go/src/testing/testing.go:1198 +0x194
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 39 [chan receive]:
testing.runTests.func1.1(0xc000106480)
	/usr/local/go/src/testing/testing.go:1517 +0x48
created by testing.runTests.func1
	/usr/local/go/src/testing/testing.go:1517 +0xc8

goroutine 5 [chan receive]:
testing.(*T).Parallel(0xc000001200)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestHeader.func1(0xc000001200)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_test.go:34 +0x44
testing.tRunner(0xc000001200, 0xc000054010)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 50 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000212000)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestUnmarshal.func4(0xc000212000)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:337 +0x30
testing.tRunner(0xc000212000, 0xc000200000)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 6 [chan receive]:
testing.(*T).Parallel(0xc000001500)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestHeader.func2(0xc000001500)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/token_test.go:51 +0x34
testing.tRunner(0xc000001500, 0x10321cd00)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 66 [runnable]:
testing.tRunner(0xc000302300, 0x10321cd80)
	/usr/local/go/src/testing/testing.go:1080
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 98 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000382300)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestUnmarshalJSON.func1(0xc000382300)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:397 +0x34
testing.tRunner(0xc000382300, 0x10321cd68)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 51 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000212300)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestUnmarshal.func4(0xc000212300)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:337 +0x30
testing.tRunner(0xc000212300, 0xc000200040)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 7 [runnable]:
testing.tRunner(0xc000001b00, 0x10321cd08)
	/usr/local/go/src/testing/testing.go:1080
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 52 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000212600)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestUnmarshal.func4(0xc000212600)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/jwt_test.go:337 +0x30
testing.tRunner(0xc000212600, 0xc000200080)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 53 [runnable]:
testing.(*T).Parallel(0xc000212900)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func1(0xc000212900)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:15 +0x2c
testing.tRunner(0xc000212900, 0x10321ccc0)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 54 [chan receive]:
testing.(*testContext).waitParallel(0xc000100410)
	/usr/local/go/src/testing/testing.go:1297 +0x130
testing.(*T).Parallel(0xc000212c00)
	/usr/local/go/src/testing/testing.go:1061 +0x2b4
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func2(0xc000212c00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:35 +0x2c
testing.tRunner(0xc000212c00, 0x10321ccc8)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 55 [runnable]:
testing.(*T).Parallel(0xc000212f00)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func3(0xc000212f00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:60 +0x2c
testing.tRunner(0xc000212f00, 0x10321ccd0)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 56 [runnable]:
testing.(*T).Parallel(0xc000213200)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func4(0xc000213200)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:80 +0x2c
testing.tRunner(0xc000213200, 0x10321ccd8)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 57 [runnable]:
testing.(*T).Parallel(0xc000213500)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func5(0xc000213500)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:105 +0x2c
testing.tRunner(0xc000213500, 0x10321cce0)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 58 [runnable]:
testing.(*T).Parallel(0xc000213800)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func6(0xc000213800)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:136 +0x34
testing.tRunner(0xc000213800, 0x10321cce8)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434

goroutine 59 [runnable]:
testing.(*T).Parallel(0xc000213b00)
	/usr/local/go/src/testing/testing.go:1060 +0x294
github.com/lestrrat-go/jwx/jwt_test.TestGHIssue10.func7(0xc000213b00)
	/Users/lestrrat/dev/src/github.com/lestrrat-go/jwx/jwt/validate_test.go:175 +0x2c
testing.tRunner(0xc000213b00, 0x10321ccf0)
	/usr/local/go/src/testing/testing.go:1194 +0x174
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x434
FAIL	github.com/lestrrat-go/jwx/jwt	0.358s
?   	github.com/lestrrat-go/jwx/jwt/internal/cmd/gentoken	[no test files]
ok  	github.com/lestrrat-go/jwx/jwt/internal/types	(cached)
ok  	github.com/lestrrat-go/jwx/jwt/openid	(cached)
ok  	github.com/lestrrat-go/jwx/x25519	(cached)
FAIL
make: *** [smoke] Error 1
```

**Comment by goccy** [comment]
`stdToken.privateClaims` ( defined at `jwt/token_gen.go` ) is accessed concurrently ... ?

**Comment by lestrrat** [comment]
It's possible (and I thought about that), but this never happens when using `encoding/json`, so... I can certainly put a lock around `stdToken`, but it does strike me as odd that this only happens when I switch to `github.com/goccy/go-json`

**Comment by goccy** [comment]
It doesn't seem to be directly related to this problem, but it seems that `encoding/json` can also cause the following error .
Perhaps, I tried to 10 times and more .

```
$ go test -race -short ./... -count=1
ok      github.com/lestrrat-go/jwx      0.572s
?       github.com/lestrrat-go/jwx/cmd/jwx      [no test files]
ok      github.com/lestrrat-go/jwx/internal/base64      0.171s
?       github.com/lestrrat-go/jwx/internal/blackmagic  [no test files]
?       github.com/lestrrat-go/jwx/internal/cmd/genreadfile     [no test files]
?       github.com/lestrrat-go/jwx/internal/ecutil      [no test files]
?       github.com/lestrrat-go/jwx/internal/fs  [no test files]
?       github.com/lestrrat-go/jwx/internal/iter        [no test files]
?       github.com/lestrrat-go/jwx/internal/jose        [no test files]
?       github.com/lestrrat-go/jwx/internal/json        [no test files]
?       github.com/lestrrat-go/jwx/internal/jwxtest     [no test files]
ok      github.com/lestrrat-go/jwx/internal/keyconv     0.579s
?       github.com/lestrrat-go/jwx/internal/pool        [no test files]
ok      github.com/lestrrat-go/jwx/jwa  0.296s
?       github.com/lestrrat-go/jwx/jwa/internal/cmd/gentypes    [no test files]
ok      github.com/lestrrat-go/jwx/jwe  1.453s
ok      github.com/lestrrat-go/jwx/jwe/internal/aescbc  0.321s
ok      github.com/lestrrat-go/jwx/jwe/internal/cipher  0.374s
?       github.com/lestrrat-go/jwx/jwe/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jwe/internal/concatkdf       0.330s
?       github.com/lestrrat-go/jwx/jwe/internal/content_crypt   [no test files]
ok      github.com/lestrrat-go/jwx/jwe/internal/keyenc  0.830s
?       github.com/lestrrat-go/jwx/jwe/internal/keygen  [no test files]
ok      github.com/lestrrat-go/jwx/jwk  6.616s
?       github.com/lestrrat-go/jwx/jwk/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jws  2.029s
?       github.com/lestrrat-go/jwx/jws/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jwt  1.309s
?       github.com/lestrrat-go/jwx/jwt/internal/cmd/gentoken    [no test files]
ok      github.com/lestrrat-go/jwx/jwt/internal/types   0.485s
ok      github.com/lestrrat-go/jwx/jwt/openid   1.060s
ok      github.com/lestrrat-go/jwx/x25519       0.418s
[/Users/goccy/Development/jwx ((bc72347...) *)]$ go test -race -short ./... -count=1
ok      github.com/lestrrat-go/jwx      0.676s
?       github.com/lestrrat-go/jwx/cmd/jwx      [no test files]
ok      github.com/lestrrat-go/jwx/internal/base64      0.284s
?       github.com/lestrrat-go/jwx/internal/blackmagic  [no test files]
?       github.com/lestrrat-go/jwx/internal/cmd/genreadfile     [no test files]
?       github.com/lestrrat-go/jwx/internal/ecutil      [no test files]
?       github.com/lestrrat-go/jwx/internal/fs  [no test files]
?       github.com/lestrrat-go/jwx/internal/iter        [no test files]
?       github.com/lestrrat-go/jwx/internal/jose        [no test files]
?       github.com/lestrrat-go/jwx/internal/json        [no test files]
?       github.com/lestrrat-go/jwx/internal/jwxtest     [no test files]
ok      github.com/lestrrat-go/jwx/internal/keyconv     0.731s
?       github.com/lestrrat-go/jwx/internal/pool        [no test files]
ok      github.com/lestrrat-go/jwx/jwa  0.358s
?       github.com/lestrrat-go/jwx/jwa/internal/cmd/gentypes    [no test files]
ok      github.com/lestrrat-go/jwx/jwe  1.716s
ok      github.com/lestrrat-go/jwx/jwe/internal/aescbc  0.181s
ok      github.com/lestrrat-go/jwx/jwe/internal/cipher  0.455s
?       github.com/lestrrat-go/jwx/jwe/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jwe/internal/concatkdf       0.499s
?       github.com/lestrrat-go/jwx/jwe/internal/content_crypt   [no test files]
ok      github.com/lestrrat-go/jwx/jwe/internal/keyenc  0.498s
?       github.com/lestrrat-go/jwx/jwe/internal/keygen  [no test files]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e9d8d]

goroutine 199 [running]:
github.com/lestrrat-go/jwx/jwk.(*AutoRefresh).doRefreshRequest(0xc0001c2120, 0x169a228, 0xc0007323c0, 0xc0001ba048, 0x16, 0x65fa28914b555101, 0x0, 0x0)
        /Users/goccy/Development/jwx/jwk/refresh.go:447 +0x52d
github.com/lestrrat-go/jwx/jwk.(*AutoRefresh).refreshLoop.func1(0xc0001c2120, 0x169a228, 0xc0007323c0, 0xc00018c180)
        /Users/goccy/Development/jwx/jwk/refresh.go:421 +0x85
created by github.com/lestrrat-go/jwx/jwk.(*AutoRefresh).refreshLoop
        /Users/goccy/Development/jwx/jwk/refresh.go:419 +0xcd1
FAIL    github.com/lestrrat-go/jwx/jwk  6.915s
?       github.com/lestrrat-go/jwx/jwk/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jws  3.407s
?       github.com/lestrrat-go/jwx/jws/internal/cmd/genheader   [no test files]
ok      github.com/lestrrat-go/jwx/jwt  1.078s
?       github.com/lestrrat-go/jwx/jwt/internal/cmd/gentoken    [no test files]
ok      github.com/lestrrat-go/jwx/jwt/internal/types   0.546s
ok      github.com/lestrrat-go/jwx/jwt/openid   1.518s
ok      github.com/lestrrat-go/jwx/x25519       0.521s
FAIL
```

**Comment by lestrrat** [comment]
That, I understand. That probably has nothing to do with `encoding/json`

**Comment by lestrrat** [comment]
For your testing, please disable that one test for AutoRefresh

**Comment by lestrrat** [comment]
I added locks around `jwt.stdToken` at [8b87dca382368a25585236460935a52b3e9252d5](https://github.com/lestrrat-go/jwx/commit/8b87dca382368a25585236460935a52b3e9252d5), and yeah the above problem went away. 

I suppose this is then okay, but it's just *feels* weird that this never happened with `encoding/json`, and seems to reproduce every time with `github.com/goccy/go-json`

**Comment by lestrrat** [comment]
@goccy oh well, the original problem is gone. Please merge #95 and close this issue? I will file another issue if I find something else.

**Comment by goccy** [comment]
OK ! I will merge #95 !

**Comment by lestrrat** [comment]
Thank you!
